//
//  CongressPerson.swift
//  Hakathon-Say_Somthing
//
//  Created by Anthony Gonzalez on 12/18/19.
//  Copyright © 2019 Mr Wonderful. All rights reserved.
//

import Foundation

struct CongressPerson {
    let name: String
    let district: Int
    let address: String
    let number: String
    let email: String
    let imageURL: String
    let description: String
    
    
    static let congressPeople: [CongressPerson] = [
    CongressPerson(name: "Peter J. Abbate, Jr.", district: 49, address: "6605 Fort Hamilton Parkway Brooklyn, NY 11219", number: "718-236-1764", email: "abbatep@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/049.jpg", description: "Peter J. Abbate, Jr., a lifelong resident of Bensonhurst, Brooklyn, has been elected by the people of Dyker Heights, Bath Beach, Bensonhurst and Borough Park to represent them in the New York State Assembly since 1986. Born on March 22, 1949, Mr. Abbate attended local schools, beginning at Regina Pacis Grammar School and on to Bishop Ford High School. He entered St. John’s University in 1967 where he earned his Bachelor of Arts degree in political science."),
    CongressPerson(name: "Thomas J. Abinanti", district: 92, address: "303 South Broadway Suite 229 Tarrytown, NY 10591", number: "914-631-1605", email: "abinantit@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/092.jpg", description: "Tom Abinanti was elected to represent the 92nd Assembly District in November 2010. The 92nd AD consists of the Towns of Greenburgh and Mount Pleasant. Prior to his election to the Assembly, Tom was elected to represent the residents of Greenburgh in the Westchester County Legislature ten times. He was seen as a leader in preserving our environment, ending gun violence, protecting women’s rights and advocating for children with special needs. Tom led the way to preserving hundreds of acres for parks/open space and passed landmark clean air and clean water legislation. He authored laws to reform Westchester’s gun regulations and to clean up the trash industry. He was instrumental in establishing the Westchester Medical Center as an independent public benefit corporation."),
    CongressPerson(name: "Carmen E. Arroyo", district: 84, address: "384 E 149th St., Suite 202 Bronx, NY 10455", number: "718-292-2901", email: "ArroyoC@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/084.jpg", description: "Carmen E. Arroyo was born in the beautiful mountainous town of Corozal, Puerto Rico. She graduated from Corozal High School and Sixto Febus Business School, where she received her Secretarial-Bookkeeper degree. Looking to build a better future for her family, Carmen moved to New York alone in 1964. She worked long hours in a factory and saved money until she was able to bring her seven children from Puerto Rico. In 1965, she sent for her children, but unable to find day care services, she was forced to receive Public Assistance. Carmen was on Public Assistance for nine months, during which time she organized the welfare mothers of her community and founded the South Bronx Action Group in 1966. The South Bronx Action Group received funding and Carmen served as the Executive Director. She expanded the notion of tenant advocacy to include the interrelated services of employment, health, adult education, and welfare. The SBAG is still in existence today."),
    CongressPerson(name: "Jake Ashby", district: 107, address: "594 Columbia Turnpike East Greenbush, NY 12061", number: "518-272-6149", email: "ashbyj@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/107.jpg", description: "Jake Ashby was elected to the New York State Assembly on April 24, 2018. His district is comprised of parts of Rensselaer, Columbia and Washington counties. As an Assemblyman, Jake will fight to roll back the SAFE Act and oppose future infringements of the Second Amendment. As a veteran he will be a strong voice for the men and women who serve our country and identify strategies with local government and businesses that will help provide the best care, support and opportunities for service members returning home. Jake believes in the need to improve infrastructure in our communities including water issues that have plagued residents of the 107th District. He remains committed to restoring public trust in state government and stimulating economic growth by reducing onerous rules and regulations burdening small businesses."),
    CongressPerson(name: "Jeffrion L. Aubry", district: 35, address: "98-09 Northern Blvd. Corona, NY 11368", number: "718-457-3615", email: "AubryJ@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/035.jpg", description: "Jeffrion L. Aubry for the 35th A.D. of Queens County was elected to the New York State Assembly in a Special Election on January 3, 1992. Assemblyman Aubry presently is the New York State Speaker Pro Tempore and member of the following committees: Ways and Means, Rules, Social Services and Governmental Employees. Assemblyman Aubry is a member of the Council of State Governments and is a “Toll Fellow,” a distinguished association of state legislators from across the country. Mr. Aubry has served as a chairman of the Board of Justice Center, a national organization which provides technical assistance to states to develop data driven consensus supported criminal justice policies to reduce crime and decrease the cost of incarceration nationwide."),
    CongressPerson(name: "William A. Barclay ", district: 120, address: "200 North Second Street Fulton, NY 13069", number: "315-598-5185", email: "BarclaW@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/120.jpg", description: "Will Barclay was first elected as a member of the New York State Assembly on November 5, 2002. He currently represents the 120th Assembly District, which includes the Oswego County towns of Albion, Amboy, Boylston, Constantia, Granby, Hastings, Mexico, New Haven, Orwell, Palermo, Parish, Redfield, Richland, Sandy Creek, Schroeppel, Scriba, Volney, West Monroe and Williamstown; the cities of Oswego and Fulton; the Onondaga County town of Lysander; and, the Jefferson County town of Ellisburg."),
    CongressPerson(name: "Brian Barnwell", district: 30, address: "55-19 69th Street Maspeth, NY 11378", number: "718-651-3185", email: "BarnwellB@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/030.jpg", description: "Brian Barnwell was born in New York City in 1986 and is a longtime Woodside resident. He comes from a middle-class family of law enforcement officers, nurses and teachers. He earned his bachelor’s in political science, cum laude, from Arizona State University and his law degree from Albany Law School. During his time in law school, Barnwell worked for two judges, the Albany County District Attorney’s Office and the Albany Law School Civil Rights and Disabilities Law Clinic. After law school, Barnwell went into private practice before working for New York City Councilman Costa Constantinides. During his time with Councilman Constantinides, Barnwell helped organize various community volunteer operations and helped countless constituents in local community matters. Barnwell also currently organizes volunteer groups that work with local churches and City Harvest to feed the needy."),
    CongressPerson(name: "Didi Barett", district: 106, address: "420 Warren Street Hudson, NY 12534", number: "518-828-1961", email: "barrettd@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/106.jpg", description: "Didi Barrett was elected to the New York State Assembly in a special election in March 2012 and is now in her fourth full term in office. A resident of the Hudson Valley for more than 30 years, she came to elected office after a career as a writer, museum professional and longtime leader of not-for-profit organizations. As a member of the Assembly, she is Chair of the Assembly Committee on Libraries and Education Technology and also serves on the Committees on Agriculture; Environmental Conservation, Mental Health and Tourism, Parks, Arts and Sports Development, as well as the Legislative Women’s Caucus."),
    CongressPerson(name: "Charles Barron", district: 60, address: "669 Vermont St. Brooklyn, NY 11207", number: "718-257-5824", email: "barronc@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/060.jpg", description: "Charles Barron has been a community activist for over 49 years. In 1969, in need of a vehicle to express his desire for justice, Barron joined the Harlem branch of the Black Panther Party. After his Black Panther experience, he attended New York City Community College, now known as New York Technical College, where he obtained an Associate's Degree. He then attended Hunter College where he acquired his Bachelor of Arts Degree in Sociology with a minor in Elementary Education."),
    CongressPerson(name: "Michael Benedetto", district: 82, address: "3602 E. Tremont Ave. Suite 201 Bronx, NY 10465", number: "718-892-2235", email: "benedettom@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/082.jpg", description: "Michael R. Benedetto was born in the Bronx in 1947 and has lived his entire life in Northeast Bronx. He attended local Catholic primary and secondary schools, and in 1969 he graduated from Iona College with a B. A. degree in History/Education. While a student at Iona College he served as President of the Student Council and was listed in Who’s Who in American Colleges. In 1971, he earned a M.A. in Social Studies/Education."),
    CongressPerson(name: "Rodneyse Bichotte", district: 42, address: "1312 Flatbush Avenue Brooklyn, NY 11210", number: "718-940-0428", email: "bichotter@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/042.jpg", description: "Rodneyse Bichotte is the Assemblymember and State Committee Woman / District Leader for New York State’s 42nd Assembly District representing Flatbush, East Flatbush, Midwood and Ditmas Park in Brooklyn. Assemblymember Rodneyse Bichotte was born and raised in Brooklyn. She is the first Haitian-American woman elected in New York City, and the first Engineer elected to the New York State Legislature."),
    CongressPerson(name: "Michael Blake", district: 79, address: "780 Concourse Village West Ground Fl. Professional Bronx, NY 10451", number: "718-538-3829", email: "BlakeM@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/079.jpg", description: "When describing the path his life has taken, Michael Blake humbly refers to the words of his mother who remarked that the family had gone “from no house to the White House.” Blake has committed himself to public service and to the empowerment of others like him, who may not have direct access to opportunities to participate in the policy and political debates that shape this nation. Blake’s family story is a testament to his achievement. His family emigrated to the U.S. from Jamaica seeking new opportunities, but facing many new challenges."),
    CongressPerson(name: "Ken Blankenbush", district: 117, address: "40 Franklin Street Suite 2 Carthage, NY 13619", number: "315-493-3909", email: "blankenbushk@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/117.jpg", description: "Assemblyman Ken Blankenbush (R,C,I) was first elected to office in 2010, representing a district that spans a large portion of the North Country from the Adirondacks in St. Lawrence County, to the quaint towns and villages of Jefferson County, to the Tug Hill Plateau and farm land in Lewis County to the Mohawk Valley in Oneida County. Blankenbush, a longtime resident of Black River, is a husband, father, grandfather, small businessman, and public servant, deeply rooted in his community."),
    CongressPerson(name: "Karl Brabenec", district: 98, address: "28 North Main St. Suite 2 Florida, NY 10921", number: "845-544-7551", email: "brabeneck@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/098.jpg", description: "Karl Brabenec was elected to serve the constituents of the 98th Assembly District on November 4, 2014. The district includes parts of Orange and Rockland counties which include Deerpark, Port Jervis, Greenville, Minisink, Warwick, Monroe, Palm Tree, Tuxedo and Ramapo. He is currently the Assistant Minority Whip for the New York State Assembly and the ranking Minority member on the Assembly Labor Committee."),
    CongressPerson(name: "Neema B. Philippe", district: 69, address: "47-10 Austell Pl 2nd Floor, Long Island City, NY 11101", number: "(347) 841-6090", email: "neemaphilippe@pursuit.org", imageURL: "https://i.imgur.com/2Gn8RNT.jpg", description: "Neema Philippe is an aspiring iOS developer with dreams of becoming the top programmer in the United States. She can be often be found coding or daydreaming about how best to surmount the issues XCode throws her away. She is also a motiviational speaker, rallying millions of devoted followers to her speeches which mainly consist of 'manifesting from the Universe'."),
    CongressPerson(name: "Edward C. Braunstein", district: 26, address: "213-33 39th Avenue Suite 238 Bayside, NY 11361", number: "718-357-3588", email: "braunsteine@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/026.jpg", description: "Assemblyman Edward C. Braunstein was born and raised in Bayside and now resides in Whitestone with his wife, Stephanie, and their two children. Assemblyman Braunstein was elected to the New York State Assembly in 2010 to represent the 26th District in Northeast Queens, which includes the neighborhoods of Auburndale, Bay Terrace, Bayside, Bayside Hills, Broadway-Flushing, Douglaston, Floral Park, Glen Oaks, Little Neck, New Hyde Park, North Shore Towers, Oakland Gardens, and Whitestone."),
    CongressPerson(name: "Harry B. Bronson", district: 138, address: "840 University Avenue Rochester, NY 14607", number: "585-244-5255", email: "bronsonh@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/138.jpg", description: "Harry Bronson was first elected to the New York State Assembly in November 2010. The 138th District includes parts of the City of Rochester and the suburban and rural towns of Henrietta and Chili. Harry’s passion for social justice, equality and fairness has defined his public service, legal and business careers. Before being elected to the state Assembly, he served in the Monroe County Legislature and held leadership positions during his entire tenure, including Minority Leader."),
    CongressPerson(name: "David Buchwald", district: 93, address: "100 S. Bedford Rd. Suite 150 Mount Kisco, NY 10549", number: "914-244-4450", email: "BuchwaldD@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/093.jpg", description: "Talking about ethics reform in government is easy; delivering results in the battle against corruption is the true challenge. But upon arriving in Albany in 2013, newly elected State Assemblyman David Buchwald started on a path towards doing something about integrity in government. He introduced an amendment to the New York State Constitution to enable courts to strip government pensions from officials convicted of corruption connected to their public duties. Assemblyman Buchwald argued this would cause potential lawbreakers to think twice before committing the crime, and free taxpayers from sending hundreds of thousands of dollars to officials who had broken the public’s trust. After a number of years overcoming obstacles in Albany, Assemblyman Buchwald’s amendment was approved in two sessions of the State Legislature. Then, on November 7, 2017, New York State voters overwhelmingly approved his pension forfeiture amendment to the state constitution (Proposal 2 on the 2017 ballot)."),
    CongressPerson(name: "Pat Burke", district: 142, address: "1074 Union Road West Seneca, NY 14224", number: "716-608-6099", email: "burkep@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/142.jpg", description: "Pat Burke is a Buffalo native, where he resides with his wife and three kids. From January of 2014 to December of 2018, Pat served the community as an Erie County Legislator. He also serves as a political science instructor at Buffalo State College. During Pat’s tenure on the legislature, his notable legislative accomplishments include a ban on microbead plastics, a repeal of Sunday Blue Laws, a million-dollar emergency fund created to combat the opioid crisis and the formation of the Erie County Broadband Committee."),
    CongressPerson(name: "Marianne Buttenschon", district: 119, address: "207 Genesee Street Rm 401 Utica, NY 13501", number: "315-732-1055", email: "buttenschonm@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/119.jpg", description: "Before winning election to the Assembly’s 119th District, Dr. Marianne Buttenschon was the Dean of Public Service and Emergency Preparedness at Mohawk Valley Community College. Her 2018 campaign for the Assembly was her first attempt at elected office. Marianne is married to Don Buttenschon, a retired public school psychologist. They have three grown children and one granddaughter. For over 30 years, Don and Marianne have operated the Buttenschon Christmas Tree Farm in the Town of Marcy, Oneida County."),
    CongressPerson(name: "Kevin M. Byrne", district: 94, address: "3 Starr Ridge Rd. Suite 204 Brewster, NY 10509", number: "845-278-2923", email: "ByrneK@nyassembly.gov", imageURL: "https://nyassembly.gov/mem/pic/094.jpg", description: "Kevin Byrne is the current assemblymember for the 94th Assembly District and serves as the ranking Minority member on the Aging Committee. He also serves on the Health, Labor, Banks, and Governmental Operations Committees. Kevin resides in Mahopac with his wife, Briana (Messina) Byrne, who has a busy career as a physician assistant (PA) at Montefiore Hospital, and their rescued Treeing Walker Coonhound, Tracker. He is the third child of his two hardworking parents. His father, Dan, continues to work as a high-voltage troubleshooter at Con Edison with the UWUA Local 1-2, and his mother, Patty, is a past 20+ year employee of Putnam Hospital Center.")
    ]
}
